/**
 * Client-safe export dari daftar kategori bisnis.
 * Dipakai di UI wizard (tidak boleh import dari $lib/server/*).
 */
export const ALL_BUSINESS_CATEGORIES = [
  { value: 'FNB_RESTO', label: 'Restoran / Warung Makan', group: 'F&B' },
  { value: 'FNB_CATERING', label: 'Katering', group: 'F&B' },
  { value: 'FNB_COFFEE_ROASTERY', label: 'Cafe / Kopi', group: 'F&B' },
  { value: 'FNB_BAR_CLUB', label: 'Bar / Club', group: 'F&B' },
  { value: 'FNB_PRODUKSI', label: 'Produksi Makanan/Minuman', group: 'F&B' },
  { value: 'FNB_FRANCHISE', label: 'Franchise F&B', group: 'F&B' },
  { value: 'RETAIL_MINIMARKET', label: 'Minimarket / Toko Kelontong', group: 'Retail' },
  { value: 'RETAIL_FASHION', label: 'Fashion / Butik Pakaian', group: 'Retail' },
  { value: 'RETAIL_BEAUTY', label: 'Kosmetik / Kecantikan', group: 'Retail' },
  { value: 'RETAIL_ELECTRONIC', label: 'Elektronik / Gadget', group: 'Retail' },
  { value: 'RETAIL_FURNITURE', label: 'Furnitur / Interior', group: 'Retail' },
  { value: 'RETAIL_JEWELRY', label: 'Perhiasan / Emas', group: 'Retail' },
  { value: 'RETAIL_PETSHOP', label: 'Pet Shop', group: 'Retail' },
  { value: 'RETAIL_SPORTS', label: 'Olahraga / Outdoor', group: 'Retail' },
  { value: 'RETAIL_BOOKSTORE', label: 'Toko Buku / ATK', group: 'Retail' },
  { value: 'RETAIL_PHARMACY', label: 'Apotek', group: 'Retail' },
  { value: 'JASA_BARBER', label: 'Barbershop / Salon', group: 'Jasa' },
  { value: 'JASA_LAUNDRY', label: 'Laundry', group: 'Jasa' },
  { value: 'JASA_TEKNIK', label: 'Service Elektronik / Bengkel', group: 'Jasa' },
  { value: 'JASA_KONSULTASI', label: 'Konsultan / Advisor', group: 'Jasa' },
  { value: 'JASA_PHOTOGRAPHY', label: 'Fotografi / Videografi', group: 'Jasa' },
  { value: 'JASA_LOGISTIK', label: 'Logistik / Ekspedisi', group: 'Jasa' },
  { value: 'JASA_CLEANING', label: 'Cleaning Service', group: 'Jasa' },
  { value: 'JASA_RECRUITMENT', label: 'Rekrutmen / HR Outsource', group: 'Jasa' },
  { value: 'HEALTH_CLINIC', label: 'Klinik / Puskesmas', group: 'Kesehatan' },
  { value: 'HEALTH_DENTAL', label: 'Klinik Gigi', group: 'Kesehatan' },
  { value: 'HEALTH_AESTHETIC', label: 'Klinik Estetik / Kecantikan', group: 'Kesehatan' },
  { value: 'HEALTH_VETERINARY', label: 'Klinik Hewan', group: 'Kesehatan' },
  { value: 'TECH_SOFTWARE', label: 'Software House / IT', group: 'Teknologi' },
  { value: 'TECH_SAAS', label: 'SaaS / Startup Digital', group: 'Teknologi' },
  { value: 'MANUFAKTUR', label: 'Manufaktur / Pabrik', group: 'Industri' },
  { value: 'CONSTRUCTION', label: 'Konstruksi / Kontraktor', group: 'Industri' },
  { value: 'AGRIBISNIS', label: 'Agribisnis / Pertanian', group: 'Industri' },
  { value: 'PROPERTY_DEV', label: 'Properti / Developer', group: 'Industri' },
  { value: 'EDUCATION_COURSE', label: 'Kursus / Lembaga Pendidikan', group: 'Edukasi' },
  { value: 'TOURISM_HOTEL', label: 'Hotel / Penginapan', group: 'Pariwisata' },
  { value: 'TOURISM_TRAVEL', label: 'Travel Agent / Wisata', group: 'Pariwisata' },
  { value: 'MEDIA_PRODUCTION', label: 'Produksi Media / Content', group: 'Media' },
  { value: 'DEFAULT', label: 'Bisnis Lainnya', group: 'Lainnya' },
];
