package com.upstyle.bizgrow.ui

sealed class Screen {
    object Login : Screen()
    object Register : Screen()
    object Units : Screen()
    object Notifications : Screen()
    object Laporan : Screen()
    object BukuBesar : Screen()
    object JurnalUmum : Screen()
    object Piutang : Screen()
    object Hutang : Screen()
    object Pos : Screen()
    object Cs : Screen()
    object Home : Screen()
    object Dashboard : Screen()
    object Finance : Screen()
    object Hr : Screen()
    object Crm : Screen()
    object Scm : Screen()
    object Orders : Screen()
    object Products : Screen()
    object Katalog : Screen()
    object Marketing : Screen()
    object Departments : Screen()
    object TrashProducts : Screen()
    object Quotations : Screen()
    object SalesOrders : Screen()
    object LeaveRequests : Screen()
    object PosVouchers : Screen()
    object CrmTasks : Screen()
    object Neraca : Screen()
    object Budget : Screen()
    object TaxRates : Screen()
    object ClosingPeriod : Screen()
    object MarketingCampaigns : Screen()
    object Pricing : Screen()
    object BusinessPlan : Screen()
    object Sosmed : Screen()
    object WebsiteBuilder : Screen()
    object HelpCenter : Screen()
    object AdvancedSettings : Screen()
    object LandingPageScreen : Screen()
    object ShopeeIntegrationScreen : Screen()
    object PosShift : Screen()
    object PosReturn : Screen()
    object Absensi : Screen()
    object Approvals : Screen()
    object Payroll : Screen()
    object LaporanWa : Screen()
    object Coa : Screen()
    object FixedAssets : Screen()
    object CrmPipeline : Screen()
    object CrmContacts : Screen()
    object CrmActivities : Screen()
    object CsInbox : Screen()
    object Profile : Screen()
    object Settings : Screen()
    object Auth : Screen()
    data class OrderDetail(val orderId: Int) : Screen()
    data class ProdukDetail(val productId: String) : Screen()
    data class TicketDetail(val ticketId: Int) : Screen()
    object StockOpname : Screen()
    object StockLogs : Screen()
    object BarcodeScanner : Screen()
    object AiChat : Screen()
    object SalesTargets : Screen()
}